name: 430 CI Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-environment:
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -f build-essential g++ cmake
  build:
    needs: setup-environment
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: g++ main.cpp -std=c++17 -o tester
